from dotenv import load_dotenv
import os

load_dotenv()

APP_TIMEZONE = os.getenv("APP_TIMEZONE", "Asia/Qyzylorda")
GOOGLE_CREDENTIALS_PATH = os.getenv("GOOGLE_CREDENTIALS_PATH", "credentials.json")
GOOGLE_TOKEN_PATH = os.getenv("GOOGLE_TOKEN_PATH", "token.pickle")
GOOGLE_TASKLIST_ID = os.getenv("GOOGLE_TASKLIST_ID", "@default")
GOOGLE_SYNC_INTERVAL_SECONDS = int(os.getenv("GOOGLE_SYNC_INTERVAL_SECONDS", "300"))
GOOGLE_CALENDAR_SYNC_DAYS = int(os.getenv("GOOGLE_CALENDAR_SYNC_DAYS", "7"))
GOOGLE_TASK_SYNC_DAYS = int(os.getenv("GOOGLE_TASK_SYNC_DAYS", "7"))
DEFAULT_DATE_ONLY_TASK_REMINDER_HOUR = int(os.getenv("DEFAULT_DATE_ONLY_TASK_REMINDER_HOUR", "9"))
DEFAULT_DATE_ONLY_TASK_REMINDER_MINUTE = int(os.getenv("DEFAULT_DATE_ONLY_TASK_REMINDER_MINUTE", "0"))
